apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: {{K8S_NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app  
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolio-app
        image: 651956850093.dkr.ecr.us-east-1.amazonaws.com/portfolio-repo:0.7
        imagePullPolicy: Never
        ports:
          - containerPort: 80             
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-service
spec:
  selector:
    app: portfolio-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP